schema: schema.graphql
extensions:
  endpoints:
    local:
      url: http://127.0.0.1:3003/graphql
      headers:
        Authorization: Bearer
      introspect: false
    prod:
      url: https://api.unlimitedcarrier.mn/graphql
      headers:
        Authorization: Bearer eyJraWQiOiJiYWNrb2ZmaWNlIiwiYXBwIjoxLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJVY1N1cHBJc3N1ZXIiLCJpYXQiOjE3NjAzNDA0MTksImV4cCI6MTc2MDM0NzYxOSwianRpIjoiY2IyZWU0MzMtNzYyNS00YWFkLWIwZmItZWFjYmE4YjRiNWU3Iiwic2NvcGVzIjoicHVibGljIGJhY2tvZmZpY2UiLCJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImJ1eWFuYmF0LmNoQGdtYWlsLmNvbSIsIm1vYmlsZSI6Ijk5MDMzNjcyIiwicm9sZSI6ImRyaXZlciJ9fQ.yqBB1rgV3_ydGgZAlFTYLQaz9adbCsdq4LUPW9CoqAkvSonNdrLdeZic9golI2JSBzbnqTz9Ao2UyWjM6_VyERCVMnfSa2BeE1YzXRABZmIzGf9H_UJBtK5CA6BnCwyHb9oRvPdM6gUri9tqO8QfR8tStTPDsUs_zCcRbYe3Sqin20l1I1DQMSsVvaD0ptBGTMfgEog-B3cnjOhoURMeOX1wyrsvoEhi4q0X5AAiz58sEfQvD7fsNYpBd6Y-ljbYaz-u6IxPiKG2OxPSJowcIyL2NQO6u_--QhhBI2zzGcpXHQ1vTFWPjv7_kICD7lcam_OlaYhP3ytzhHqvt7WS4g
      introspect: true
